### ISSUE TITLE
random crashes while on heroku

### ISSUE THREAD

**Issue by cfanoulis** [cfanoulis/netherite-golem#4]
u gh found the crash, stack trace is

```2021-12-05T20:21:16.146559+00:00 heroku[router]: at=info method=POST path="/events/handle" host=radiant-journey-69255.herokuapp.com request_id=24faafef-3db2-4753-b5a7-6fded44bf8f7 fwd="54.196.69.144" dyno=web.1 connect=0ms service=3ms status=200 bytes=758 protocol=https

2021-12-05T20:21:17.126713+00:00 app[web.1]: TypeError: Cannot read properties of undefined (reading 'match')

2021-12-05T20:21:17.126724+00:00 app[web.1]:     at EventsService.handleMessage (file:///app/src/events/events.service.ts:20:39)

2021-12-05T20:21:17.126724+00:00 app[web.1]:     at EventsController.handleSlackEvent (file:///app/src/events/events.controller.ts:22:31)

2021-12-05T20:21:17.126725+00:00 app[web.1]:     at /app/node_modules/@nestjs/core/router/router-execution-context.js:38:29

2021-12-05T20:21:17.126725+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)

2021-12-05T20:21:17.126725+00:00 app[web.1]:     at /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28

2021-12-05T20:21:17.126726+00:00 app[web.1]:     at /app/node_modules/@nestjs/core/router/router-proxy.js:9:17

2021-12-05T20:21:17.172917+00:00 app[web.1]: error Command failed with exit code 1.

2021-12-05T20:21:17.173189+00:00 app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
currently focusing on smth else, so this is up for grabs!

**Comment by cfanoulis** [comment]
claiming this as fixed in 8dd14c6a65db738c4f9241e59baf4053e51b3c9f
